repos:
-   repo: https://github.com/psf/black
    rev: 21.11b0
    hooks:
    -   id: black
        language_version: python3.9

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    -   id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
