version: '3.4'

services:

  db:
    image: postgres:13-alpine
    container_name: "db"
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - netw

networks:
  netw:
    driver: bridge

volumes:
  db_data:
